apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-ingress
  namespace: vaultwarden
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ YOUR_VW_APP_DOMAIN }}
    http:
      paths:
      - backend:
          service:
            name: vaultwarden-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ YOUR_VW_APP_DOMAIN }}
