apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.32.4-alpine
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: vaultwarden-env-secret
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
          volumeMounts:
            - name: vaultwarden-storage
              mountPath: /data
      volumes:
        - name: vaultwarden-storage
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
      nodeSelector:
        kubernetes.io/arch: arm64
